MetaDataFormat: "yaml"
theme: "hugo-finisterre"
contentdir: "content"
layoutdir: "layouts"
datadir: "data"
staticdir: "static"
themesdir: "themes"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
pygmentsStyle: "zenburn"
baseURL: "https://traversaro.github.io/"
indexes:
  category: "categories"
  tag: "tags"
title: "Silvio Traversaro"
copyright: "&copy; 2020 Silvio Traversaro"
canonifyUrls: false
relativeUrls: true
enableRobotsTXT: true
ignoreFiles: [ "~$", "^\\.", "\\.#", "\\.Rmd$", "_files$", "_cache$", "Corel Auto-Preserve$"]

menu:
  main:
      #- Name: "Research"
      #  URL: "/research/"
      #  Weight: 3
      - Name: "Publications"
        URL: "/publications/"
        Weight: 4
      #- Name: "Blog"
      #  URL: "/post/"
      #  Weight: 7
      #- Name: "About"
      #  URL: "/about/"
      #  Weight: 9
permalinks:
  post: /post/:year/:month/:day/:slug
  news: /news/:year/:month/:day/:slug
markup:
  defaultMarkdownHandler: goldmark
  blackfriday:
    smartypants: true
    angledQuotes: false
    fractions: false
    smartDashes: true
    latexDashes: true
    hrefTargetBlank: true
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
params:
  AuthorName: "Silvio Traversaro"
  bio_name: "Silvio Traversaro"
  bio_twitter: "sitraversaro"
  cv_file: "traversaro_cv.pdf"
  organization: "Italian Institute of Technology"
  repository: "https://github.com/traversaro/traversaro.github.io"
  mathjax: true
  mhchem: true
  avatar: "profile.jpg"
  front_page_img: "profile.jpg"
  email: "silvio@traversaro.it"
  pubs_count: 4
  teach_count: 0
  post_count: 0
  news_count: 0
  news_current_months: 0
  news_post_count: 0
  social:
    email:
      priority: 2
      icon: "envelope"
      icon_pack: "fa"
      icon_weight: "s"
      link: "mailto:silvio@traversaro.it"
      text: "silvio@traversaro.it"
    twitter:
      priority: 10
      icon: "twitter"
      icon_pack: "fa"
      icon_weight: "b"
      link: "https://twitter.com/sitraversaro"
      text: "@sitraversaro"
      on_site: "Twitter"
    github:
      priority: 5
      icon: "github"
      icon_pack: "fa"
      icon_weight: "b"
      link: "https://github.com/traversaro"
      text: "traversaro"
      on_site: "GitHub"
    orcid:
      priority: 3
      icon: "orcid"
      icon_pack: "ai"
      link: "https://orcid.org/0000-0002-9283-6133"
      text: "0000-0002-9283-6133"
      site: "ORCID:"
    google_scholar:
      priority: 4
      icon: "google-scholar"
      icon_pack: "ai"
      link: "https://scholar.google.com/citations?user=c2riNzgAAAAJ"
      text: "Google Scholar"
    iit: 
      priority: 11 
      icon: "university"
      icon_pack: "fa"
      link: "https://www.iit.it/people/silvio-traversaro"
      text: "iit.it/people/silvio-traversaro"

taxonomies:
  - category: "categories"
  - tag:      "tags"
