name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true 
    
    - name: Print GitHub context
      env:
        GITHUB_EVENT: ${{ github.event_name }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        echo $GITHUB_EVENT $GITHUB_REF
    
    - name: Generate Hugo Website
      run: |
        # workaround https://github.com/jgm/pandoc-citeproc/issues/420#issuecomment-549047862
        export LANG=en_US.UTF-8
        # Install dependencies 
        sudo apt install python3 python3-pybtex pandoc-citeproc
        sudo snap install hugo
        # Generate bibliography pages
        cd bibliography
        python3 process_bibliography.py traversaro_pubs.bib
        cd .. 
        # Run Hugo
        hugo -D

    - name: Deploy
      if: github.event_name == 'push' && (github.ref == 'refs/heads/source')
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: public
